"""Write governance/SESSION_HANDOUT.md from AUDIT_STATE.json.

The handout is what the next agent reads first. It must give a complete picture
of where work stands without requiring the agent to traverse YAML files
manually.
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_PATH = REPO_ROOT / "governance" / "AUDIT_STATE.json"
HANDOUT_PATH = REPO_ROOT / "governance" / "SESSION_HANDOUT.md"
SESSION_END_PATH = REPO_ROOT / "governance" / "SESSION_END.md"


def main() -> int:
    if not STATE_PATH.exists():
        print(f"[session_start] {STATE_PATH} missing — run `make audit` first", file=sys.stderr)
        return 1
    state = json.loads(STATE_PATH.read_text())
    summary = state["summary"]
    findings = state["findings"]
    migrations = state["migrations"]

    open_findings = [f for f in findings if f["status"] == "open"]
    in_progress_findings = [f for f in findings if f["status"] == "in_progress"]

    open_findings.sort(key=lambda f: (f.get("category") or "", f.get("id") or ""))

    lines: list[str] = []
    lines.append(f"# Session Handout — {datetime.now(UTC).strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append(
        f"Generated by `make session-start` from `{STATE_PATH.relative_to(REPO_ROOT)}` "
        f"(state SHA: `{state.get('git_head_sha', 'unknown')[:8]}`)."
    )
    lines.append("")
    lines.append("## Snapshot")
    lines.append("")
    lines.append(f"- Findings: total={summary['findings_total']}, "
                 f"open={summary['findings_open']}, "
                 f"in_progress={summary['findings_in_progress']}, "
                 f"closed={summary['findings_closed']}, "
                 f"historical={summary['findings_closed_historical']}")
    lines.append(f"- Migrations: total={summary['migrations_total']}, "
                 f"in_progress={summary['migrations_in_progress']}")
    lines.append("")

    if summary.get("open_by_category"):
        lines.append("## Open by category")
        lines.append("")
        for cat, n in sorted(summary["open_by_category"].items()):
            lines.append(f"- `{cat}`: {n}")
        lines.append("")

    if in_progress_findings:
        lines.append("## In progress")
        lines.append("")
        for f in in_progress_findings:
            lines.append(f"- **{f['id']}** — {f['title']} (`{f['path']}`)")
        lines.append("")

    if open_findings:
        lines.append("## Open findings (work queue)")
        lines.append("")
        for f in open_findings:
            lines.append(f"- **{f['id']}** ({f['category']}) — {f['title']}")
            lines.append(f"  - YAML: `{f['path']}`")
            if f.get("verification_script"):
                lines.append(f"  - Verification: `{f['verification_script']}`")
            else:
                lines.append("  - Verification: **TODO — write the script first**")
        lines.append("")
        recommended = open_findings[0]
        lines.append(f"## Recommended next action")
        lines.append("")
        lines.append(f"Pick up **{recommended['id']}** — {recommended['title']}.")
        lines.append("")
    else:
        lines.append("## Open findings")
        lines.append("")
        lines.append("None. The queue is empty.")
        lines.append("")
        lines.append("## Recommended next action")
        lines.append("")
        lines.append(
            "No open findings. Either file new findings against newly discovered "
            "drift, work an `in_progress` finding to close, or hand off via "
            "`make session-end`."
        )
        lines.append("")

    if SESSION_END_PATH.exists():
        lines.append("## Prior session handoff")
        lines.append("")
        lines.append(f"See `{SESSION_END_PATH.relative_to(REPO_ROOT)}`.")
        lines.append("")

    if state.get("validation_errors"):
        lines.append("## ⚠ Validation errors")
        lines.append("")
        for err in state["validation_errors"]:
            lines.append(f"- {err}")
        lines.append("")

    HANDOUT_PATH.write_text("\n".join(lines))
    print(f"[session_start] wrote {HANDOUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
